### PR TITLE
Convert less to sass

### PR DESCRIPTION
**Pull request by joelpittet**

### CODE REVIEW

**Comment by joelpittet** [comment]
I ignored the map files, they will build for development. It just adds the comment to the end of the CSS to tell where they are (when they exist). Maybe there is a better way to do this?

**Comment by occupant** [comment]
I thought I had seen 404s when the map files are missing. I can test this quickly.

**Comment by occupant** [comment]
Yes, Safari is showing a 404 when the .map file is missing. It's ok in Chrome and Firefox. Not sure if this is a bug or a feature :)

**Comment by joelpittet** [comment]
Sounds like both...

**Comment by occupant** [comment]
As the .map issue is only in Safari and only when the inspector is open (does not create a new http request before that), I'm ok with the .map file references being included.

I've confirmed this by loading the getbootstrap.com site, which has an error in Safari, into webpagetest.org using IOS11/iPhone 8. [The results](https://www.webpagetest.org/result/180205_QA_6bfe3edc5004079ce291b4f03680117f/) support that there is no additional http request.

**Pull request merged**
