### PR TITLE
Cleanup and updates for 1.0 release

### PR DESCRIPTION
**Pull request by occupant**
Hi Joel, hoping you can take a look at this to make sure I didn't do anything strange. I'd like to create a v1.0 release of Galactus. Most of this is housecleaning and combing for consistency. 

If it looks ok to you, I can run a lint and get an initial release out.

### CODE REVIEW

**Comment by occupant** [comment]
Yes, moving to SCSS is on my internal todo list. I'm all for it. Is there anything specific you need to run your version of libsass?

I like the idea of excluding the unit.custom.css entirely. I have updated the readme to suggest using this as a base theme and [CLF](https://github.com/ubc-web-services/clf) as the child theme (maybe that could use a rethink on the name though). Excluding the unit.custom.css from galactus will make that suggestion a little harder to ignore.

To make the parent / child relationship easier to understand, I need to get the composer file sorted out for the CLF theme. I'll take a crack at that.

**Comment by joelpittet** [comment]
You could do what others do and create a 'starter' theme? That way it doesn't live in the same project in the end.  I know basic's whole theme is like that but zen and others have a starter theme to copy from. I'll try to find examples.

I'll create a separate PR for SASS maybe after this is committed but before you tag it?

**Comment by occupant** [comment]
Right, that's the plan (if I follow correctly). I've pulled the child theme out of this one and am pointing to it via the docs. And then I'd like to get the composer file in the child theme to require this one.

I'll merge this after I pull out the unit.custom.css so you can make your PR.

**Comment by occupant** [comment]
Ok, merged :)

**Pull request merged**
